configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\OneTimePassword" -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet publish "src\OneTimePassword" -c %CONFIGURATION% --no-build-o artifacts\OneTimePassword
test_script:
- dotnet test "test\OneTimePassword.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
