name: Test Runner

on: [push]

jobs:

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test with .NET Core CLI
      uses: baruchiro/github-actions@0.0.1
      args: test
