name: Test CI

on: [push]

jobs:

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install .NET Core CLI
    - uses: baruchiro/github-actions@0.0.1
    - name: Test solution
    - run: dotnet test
